### ISSUE TITLE
jeesite-api是在jeesite的基础上新增了移动服务端快速开发的框架

### ISSUE THREAD

**Issue by sheldonshen** [javyuan/jeesite-api#1]
公司最近的项目采用了jeesite做后台管理的快速开发框架,目前也需要提供移动服务端的接口(主要是android),想问下你的移动服务端大致是怎么做的,也提供自动代码生成吗?谢谢.

**Comment by javyuan** [comment]
没有自动生成，只是提供了个demo，在api目录里是提供的接口，在admin里是后台管理。

**Comment by sheldonshen** [comment]
明白了.
